services:
  webserver:
    # project https://github.com/nextcloud/docker
    build: docker/webserver
    container_name: ${CONTAINER_NAME_WEBSERVER:-webserver}
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - database:/app/databases
  seleniumfirefox:
    image: selenium/standalone-firefox:4.35
    container_name: ${CONTAINER_NAME_SELENIUM:-seleniumfirefox}
    shm_size: 2gb
    ports:
      - "127.0.0.1:4444:4444"
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_TEST:-test}
    environment:
      SELENIUM_HOSTNAME: seleniumfirefox
    volumes:
      - ./src:/code/src
      - database:/app/databases
    depends_on:
      - seleniumfirefox
      - webserver
volumes:
  database:
    name: ${DOCKER_VOLUME_DATABASE:-volume_database}